apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/ccq18/kadm-release-console
  newName: ghcr.io/ccq18/kadm-release-console
  newTag: sha-dd810af
