apiVersion: v1
kind: Secret
metadata:
  name: kadm-secrets
  namespace: kadm
type: Opaque
stringData:
  GITHUB_TOKEN: ghp_replace_me
  ARGOCD_BASE_URL: http://argocd-server.argocd.svc.cluster.local
  ARGOCD_TOKEN: argocd_replace_me
