apiVersion: v1
kind: Service
metadata:
  name: onecd
  namespace: onecd
  labels:
    app.kubernetes.io/name: onecd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: onecd
  ports:
    - name: http
      port: 80
      targetPort: http
